spring.application.name=DailyQuestHelper

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.time-zone=Asia/Seoul

server.port=${PORT:8080}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Gmail API
gmail.application.name=Daily_Quest_Helper
gmail.client.id=${GMAIL_CLIENT_ID}
gmail.client.secret=${GMAIL_CLIENT_SECRET}
gmail.refresh.token=${GMAIL_REFRESH_TOKEN}
gmail.sender.email=${GMAIL_SENDER_EMAIL}
gmail.sender.name=${GMAIL_SENDER_NAME}